---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-mongodata
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: orders-db
    product: sockshop
    stage: dev
    tier: data
    version: "1.1"
  name: orders-db
  namespace: dev
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      name: orders-db
      product: sockshop
      stage: dev
      tier: data
      version: "1.1"
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        dynatrace/instrument: "false"
        pipeline.build: 1.1.1.0022
        pipeline.project: sockshop
        pipeline.stage: dev
        sidecar.istio.io/inject: "false"
        support.channel: '#support-sockshop-data'
        support.contact: mary.poppins@sockshop.com
      creationTimestamp: null
      labels:
        name: orders-db
        product: sockshop
        stage: dev
        tier: data
        version: "1.1"
    spec:
      containers:
      - env:
        - name: MONGODB_ADMIN_PASSWORD
          value: password
        - name: MONGODB_USER
          value: user
        - name: MONGODB_PASSWORD
          value: password
        - name: MONGODB_DATABASE
          value: orders-db
        image: mongo
        imagePullPolicy: Always
        name: orders-db
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: orders-db-mongodata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: orders-db-mongodata
        persistentVolumeClaim:
          claimName: orders-db-mongodata
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: dev
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: orders-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-mongodata
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: orders-db
    product: sockshop
    stage: prod
    tier: data
    version: "1.0"
  name: orders-db
  namespace: production
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      name: orders-db
      product: sockshop
      stage: prod
      tier: data
      version: "1.0"
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        dynatrace/instrument: "false"
        pipeline.build: 1.0.2.0114
        pipeline.project: sockshop
        pipeline.stage: prod-stable
        sidecar.istio.io/inject: "false"
        support.channel: '#support-sockshop-data'
        support.contact: mary.poppins@sockshop.com
      creationTimestamp: null
      labels:
        name: orders-db
        product: sockshop
        stage: prod
        tier: data
        version: "1.0"
    spec:
      containers:
      - env:
        - name: MONGODB_ADMIN_PASSWORD
          value: password
        - name: MONGODB_USER
          value: user
        - name: MONGODB_PASSWORD
          value: password
        - name: MONGODB_DATABASE
          value: orders-db
        image: mongo
        imagePullPolicy: Always
        name: orders-db
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: orders-db-mongodata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: orders-db-mongodata
        persistentVolumeClaim:
          claimName: orders-db-mongodata
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: production
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: orders-db
